import { Day, Subject } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'cs23511',
    code: 'CS23511',
    name: 'Theory of Computation',
    teachers: [
      {
        id: 'cs23511-t1',
        name: 'Akiladevi R',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B210', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B218', type: 'Theory' },
          { day: Day.Tuesday, startTime: '16:00', endTime: '16:50', location: 'B210', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'A311', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t2',
        name: 'Jeya Mohan H',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'A204', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'A308', type: 'Theory' },
          { day: Day.Tuesday, startTime: '16:00', endTime: '16:50', location: 'A308', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'B415', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t3',
        name: 'K Ananthajothi',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B322', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B322', type: 'Theory' },
          { day: Day.Tuesday, startTime: '16:00', endTime: '16:50', location: 'B222', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'B212', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t4',
        name: 'Punitha S',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B321', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B325', type: 'Theory' },
          { day: Day.Tuesday, startTime: '16:00', endTime: '16:50', location: 'A102', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'B404', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t5',
        name: 'S Vinothini',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B410', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B415', type: 'Theory' },
          { day: Day.Tuesday, startTime: '16:00', endTime: '16:50', location: 'A302', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'A308', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t6',
        name: 'Akiladevi R',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B211', type: 'Theory' },
          { day: Day.Friday, startTime: '15:00', endTime: '15:50', location: 'A102', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A311', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B221', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t7',
        name: 'Jeya Mohan H',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B415', type: 'Theory' },
          { day: Day.Friday, startTime: '15:00', endTime: '15:50', location: 'A304', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A110', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'A204', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t8',
        name: 'K Ananthajothi',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B402', type: 'Theory' },
          { day: Day.Friday, startTime: '15:00', endTime: '15:50', location: 'B320', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A108', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B219', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t9',
        name: 'Punitha S',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B220', type: 'Theory' },
          { day: Day.Friday, startTime: '15:00', endTime: '15:50', location: 'B218', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A109', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B222', type: 'Theory' },
        ],
      },
      {
        id: 'cs23511-t10',
        name: 'S Vinothini',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'A203', type: 'Theory' },
          { day: Day.Friday, startTime: '15:00', endTime: '15:50', location: 'B408', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A303', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B411', type: 'Theory' },
        ],
      },
    ],
  },
  {
    id: 'cs23512',
    code: 'CS23512',
    name: 'Fundamentals of Mobile Computing',
    teachers: [
      {
        id: 'cs23512-t2',
        name: 'Bhavani M',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B408', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B412', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'A302', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t3',
        name: 'E M Malathy',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B325', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B320', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'B210', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t4',
        name: 'Parthasarathy Chandravinothan',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'A102', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B409', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'A203', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t5',
        name: 'Ponmani S',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'B219', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'B220', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'B221', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t6',
        name: 'Sathiyavathi S',
        department: 'Computer Science',
        group: 4,
        slots: [
          { day: Day.Friday, startTime: '13:20', endTime: '14:10', location: 'A302', type: 'Theory' },
          { day: Day.Friday, startTime: '14:10', endTime: '15:00', location: 'A102', type: 'Theory' },
          { day: Day.Wednesday, startTime: '11:00', endTime: '11:50', location: 'B411', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t7',
        name: 'Bhavani M',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B408', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A102', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B322', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t8',
        name: 'Chettiyar Vani Vivekanand',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'A311', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A205', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B212', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t9',
        name: 'Parthasarathy Chandravinothan',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B213', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A309', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B218', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t10',
        name: 'Ponmani S',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'A110', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A310', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B415', type: 'Theory' },
        ],
      },
      {
        id: 'cs23512-t11',
        name: 'Sathiyavathi S',
        department: 'Computer Science',
        group: 5,
        slots: [
          { day: Day.Friday, startTime: '10:00', endTime: '10:50', location: 'B411', type: 'Theory' },
          { day: Day.Monday, startTime: '16:00', endTime: '16:50', location: 'A103', type: 'Theory' },
          { day: Day.Thursday, startTime: '09:00', endTime: '09:50', location: 'B321', type: 'Theory' },
        ],
      }
    ],
  },
  {
    id: 'cs23531',
    code: 'CS23531',
    name: 'Web Programming',
    teachers: [
      {
        id: 'cs23531-t1',
        name: 'Anantha Sivaprakasam S',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '08:50', location: 'A102', type: 'Theory' },
          { day: Day.Monday, startTime: '09:00', endTime: '09:50', location: 'A102', type: 'Theory' },
          { day: Day.Thursday, startTime: '10:00', endTime: '11:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B302', type: 'Theory' },
        ],
      },
      {
        id: 'cs23531-t2',
        name: 'Duraimurugan N',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Friday, startTime: '16:00', endTime: '16:50', location: 'A304', type: 'Theory' },
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'CLASSROOM', type: 'Theory' },
          { day: Day.Thursday, startTime: '10:00', endTime: '11:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '08:50', location: 'A309', type: 'Theory' },
          { day: Day.Tuesday, startTime: '09:00', endTime: '09:50', location: 'A308', type: 'Theory' },
        ],
      },
      {
        id: 'cs23531-t3',
        name: 'Karthi S',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Thursday, startTime: '10:00', endTime: '10:50', location: 'B404', type: 'Theory' },
          { day: Day.Thursday, startTime: '11:00', endTime: '11:50', location: 'A204', type: 'Theory' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'TLFR1/2', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B405', type: 'Theory' },
        ],
      },
      {
        id: 'cs23531-t4',
        name: 'Senthil Kumar SS',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '08:50', location: 'A309', type: 'Theory' },
          { day: Day.Monday, startTime: '09:00', endTime: '09:50', location: 'A303', type: 'Theory' },
          { day: Day.Thursday, startTime: '10:00', endTime: '11:40', location: 'TLGL3/4', type: 'Lab' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'A203', type: 'Theory' },
        ],
      },
      {
        id: 'cs23531-t5',
        name: 'Shyni M',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '08:50', location: 'B322', type: 'Theory' },
          { day: Day.Monday, startTime: '09:00', endTime: '09:50', location: 'B409', type: 'Theory' },
          { day: Day.Thursday, startTime: '10:00', endTime: '11:40', location: 'TLGL2', type: 'Lab' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'PROGRAMMING', type: 'Theory' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B403', type: 'Theory' },
        ],
      },
      {
        id: 'cs23531-t6',
        name: 'Anantha Sivaprakasam S',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'TLFR4/5', type: 'Lab' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A202', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B415', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: '1500', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'CLASSROOM', type: 'Theory' },
        ],
      },
      {
        id: 'cs23531-t7',
        name: 'Duraimurugan N',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'CLASSROOM', type: 'Theory' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A103', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B321', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'B213', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'KSL03', type: 'Lab' },
        ],
      },
      {
        id: 'cs23531-t8',
        name: 'Karthi S',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'TLGL2', type: 'Lab' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A303', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'A205', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'A303', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'TLGL2', type: 'Lab' },
        ],
      },
      {
        id: 'cs23531-t9',
        name: 'Senthil Kumar SS',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'PROGRAMMING', type: 'Theory' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A304', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B408', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'A109', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'KSL03', type: 'Lab' },
        ],
      },
      {
        id: 'cs23531-t10',
        name: 'Shyni M',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'TIFAC', type: 'Lab' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A310', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B212', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: '08:50', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'CLASSROOM', type: 'Theory' },
        ],
      },
    ],
  },
  {
    id: 'cs23532',
    code: 'CS23532',
    name: 'Computer Networks',
    teachers: [
      {
        id: 'cs23532-t1',
        name: 'Balachandar J',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: '10:50', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLGL3/4', type: 'Lab' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'OO', type: 'Theory' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'CLASSROOM', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'CLASSROOM', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t2',
        name: 'K Anand',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B405', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'TLGL2', type: 'Lab' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLGL1', type: 'Lab' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B415', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B415', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t3',
        name: 'R Sabitha',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: '10:50', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: '12:50', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLGL2', type: 'Lab' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'OO', type: 'Theory' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B412', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t4',
        name: 'Shafiya Banu M',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B221', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'TLGL3/4', type: 'Lab' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLFR4/5', type: 'Lab' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'B403', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'CLASSROOM', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t5',
        name: 'Tamilarasu P',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: '10:50', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'TLGL1', type: 'Lab' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLFL4/5', type: 'Lab' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'CLASSROOM', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'CLASSROOM', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t6',
        name: 'Balachandar J',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'TLGL1', type: 'Lab' },
          { day: Day.Thursday, startTime: '11:00', endTime: '11:50', location: 'B211', type: 'Theory' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'TLFL1/2', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B321', type: 'Theory' },
          { day: Day.Tuesday, startTime: '15:00', endTime: '15:50', location: 'A102', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t7',
        name: 'K Anand',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'TLFR4/5', type: 'Lab' },
          { day: Day.Thursday, startTime: '10:00', endTime: '10:50', location: 'A310', type: 'Theory' },
          { day: Day.Thursday, startTime: '11:00', endTime: '11:50', location: 'B210', type: 'Theory' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: '09:40', type: 'Theory' },
          { day: Day.Tuesday, startTime: '15:00', endTime: '15:50', location: 'A203', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t8',
        name: 'R Sabitha',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'CLASSROOM', type: 'Theory' },
          { day: Day.Thursday, startTime: '10:00', endTime: '10:50', location: 'B302', type: 'Theory' },
          { day: Day.Thursday, startTime: '11:00', endTime: '11:50', location: 'B321', type: 'Theory' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'TLGL1', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B220', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t9',
        name: 'Shafiya Banu M',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'TLGL2', type: 'Lab' },
          { day: Day.Thursday, startTime: '10:00', endTime: '10:50', location: 'B221', type: 'Theory' },
          { day: Day.Thursday, startTime: '11:00', endTime: '11:50', location: 'B222', type: 'Theory' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'TLFL4/5', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B320', type: 'Theory' },
        ],
      },
      {
        id: 'cs23532-t10',
        name: 'Tamilarasu P',
        department: 'Computer Science',
        group: 2,
        slots: [
          { day: Day.Monday, startTime: '08:00', endTime: '09:40', location: 'TLFL4/5', type: 'Lab' },
          { day: Day.Thursday, startTime: '10:00', endTime: '10:50', location: 'A302', type: 'Theory' },
          { day: Day.Thursday, startTime: '11:00', endTime: '11:50', location: 'A305', type: 'Theory' },
          { day: Day.Tuesday, startTime: '08:00', endTime: '09:40', location: 'TLGL2', type: 'Lab' },
          { day: Day.Tuesday, startTime: '12:00', endTime: '12:50', location: 'B408', type: 'Theory' },
        ],
      },
    ],
  },
  {
    id: 'cs23533',
    code: 'CS23533',
    name: 'Foundations of Artificial Intelligence',
    teachers: [
      {
        id: 'cs23533-t1-1',
        name: 'Anitha M B1',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B408', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'KFR01', type: 'Theory' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'B402', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B411', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t1-2',
        name: 'Anitha M B2',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B408', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLFR3', type: 'Lab' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'B402', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B411', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t2-1',
        name: 'Divya M B1',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B211', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'KFR04', type: 'Theory' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'B213', type: 'Theory' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B219', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t2-2',
        name: 'Divya M B2',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B211', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'JL2', type: 'Theory' },
          { day: Day.Tuesday, startTime: '14:10', endTime: '15:00', location: 'B213', type: 'Theory' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B219', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t3-1',
        name: 'P Kumar B1',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B321', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'TLFR3', type: 'Lab' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B403', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B320', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t3-2',
        name: 'P Kumar B2',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B321', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'KFL02', type: 'Lab' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B403', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B320', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t4-1',
        name: 'P Muneeshwari B1',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B213', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'TLGL4', type: 'Lab' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B221', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B219', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t4-2',
        name: 'P Muneeshwari B2',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'B213', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'TLGL4', type: 'Lab' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'B221', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'B219', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t5-1',
        name: 'Vinodh Kumar S B1',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'A308', type: 'Theory' },
          { day: Day.Thursday, startTime: '13:20', endTime: '15:00', location: 'JL2', type: 'Theory' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'A311', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'A309', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t5-2',
        name: 'Vinodh Kumar S B2',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '12:00', endTime: '12:50', location: 'A308', type: 'Theory' },
          { day: Day.Thursday, startTime: '15:00', endTime: '16:40', location: 'KFR03', type: 'Theory' },
          { day: Day.Wednesday, startTime: '10:00', endTime: '10:50', location: 'A311', type: 'Theory' },
          { day: Day.Wednesday, startTime: '13:20', endTime: '14:10', location: 'A309', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t6-1',
        name: 'Anitha M B1',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'TLGL4', type: 'Lab' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A108', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B401', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'B403', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t6-2',
        name: 'Anitha M B2',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A108', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B401', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'B403', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'KFL02', type: 'Lab' },
        ],
      },
      {
        id: 'cs23533-t7',
        name: 'Divya M',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '14:10', endTime: '15:00', location: 'A205', type: 'Theory' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A204', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'CLASSROOM', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'CLASSROOM', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t8',
        name: 'P Kumar',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'TLGL1', type: 'Lab' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A205', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B405', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'B410', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t9',
        name: 'P Muneeshwari',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '13:20', endTime: '15:00', location: 'MON_L4', type: 'Theory' },
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A102', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B220', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'B221', type: 'Theory' },
        ],
      },
      {
        id: 'cs23533-t10',
        name: 'Vinodh Kumar S',
        department: 'Computer Science',
        group: 3,
        slots: [
          { day: Day.Monday, startTime: '15:00', endTime: '15:50', location: 'A309', type: 'Theory' },
          { day: Day.Thursday, startTime: '08:00', endTime: '08:50', location: 'B219', type: 'Theory' },
          { day: Day.Wednesday, startTime: '14:10', endTime: '15:00', location: 'B220', type: 'Theory' },
          { day: Day.Wednesday, startTime: '15:00', endTime: '16:40', location: 'TLFR1/2', type: 'Lab' },
        ],
      },
    ],
  },
  {
    id: 'cs23pe33',
    code: 'CS23PE33',
    name: 'Professional Elective (Low Code)',
    teachers: [
      {
        id: 'cs23pe33-t1',
        name: 'S. Kaviya',
        department: 'Computer Science',
        group: 1,
        slots: [
          { day: Day.Friday, startTime: '08:00', endTime: '08:50', location: 'ANEW104', type: 'Theory' },
          { day: Day.Friday, startTime: '09:00', endTime: '09:50', location: 'ANEW104', type: 'Theory' },
          { day: Day.Tuesday, startTime: '10:00', endTime: '11:40', location: 'KSL03', type: 'Lab' },
        ],
      },
      {
        id: 'cs23pe33-t2',
        name: 'Aswana Lal',
        department: 'Computer Science',
        group: 6,
        slots: [
          { day: Day.Monday, startTime: '10:00', endTime: '11:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Tuesday, startTime: '10:00', endTime: '10:50', location: 'ANEW104', type: 'Theory' },
          { day: Day.Tuesday, startTime: '11:00', endTime: '11:50', location: 'ANEW104', type: 'Theory' },
        ],
      },
      {
        id: 'cs23pe33-t3',
        name: 'Bhuvaneswaran B',
        department: 'Computer Science',
        group: 6,
        slots: [
          { day: Day.Friday, startTime: '08:00', endTime: '09:40', location: 'KSL03', type: 'Lab' },
          { day: Day.Monday, startTime: '10:00', endTime: '10:50', location: 'ANEW104', type: 'Theory' },
          { day: Day.Monday, startTime: '11:00', endTime: '11:50', location: 'ANEW104', type: 'Theory' },
        ],
      },
      {
        id: 'cs23pe33-t4',
        name: 'Pravin P',
        department: 'Computer Science',
        group: 6,
        slots: [
          { day: Day.Monday, startTime: '10:00', endTime: '10:50', location: 'A104', type: 'Theory' },
          { day: Day.Monday, startTime: '11:00', endTime: '11:50', location: 'A104', type: 'Theory' },
          { day: Day.Wednesday, startTime: '08:00', endTime: '09:40', location: 'KSL03', type: 'Lab' },
        ],
      }
    ],
  },
];

export const DAYS_ORDER = [
  Day.Monday,
  Day.Tuesday,
  Day.Wednesday,
  Day.Thursday,
  Day.Friday,
  Day.Saturday,
];

export const GRID_START_HOUR = 8;  // 08:00
export const GRID_END_HOUR   = 17; // 17:00
export const GRID_TOTAL_MINS = (GRID_END_HOUR - GRID_START_HOUR) * 60; // 720 mins
